package dev.persefonia.medialibrary.application.upload;

public enum UploadValidationErrorCode {
    ORIGINAL_FILENAME_REQUIRED,
    DECLARED_SIZE_REQUIRED,
    FILE_EMPTY,
    FILE_TOO_LARGE,
    CONTENT_TYPE_REQUIRED,
    CONTENT_TYPE_NOT_ALLOWED,
    FILE_EXTENSION_REQUIRED,
    FILE_EXTENSION_NOT_ALLOWED,
    CONTENT_TYPE_EXTENSION_MISMATCH,
    MAGIC_BYTES_MISMATCH,
    DECLARED_SIZE_MISMATCH,
    CHECKSUM_CALCULATION_FAILED,
    STORAGE_WRITE_FAILED
}
