spring:
  datasource:
    hikari:
      maximum-pool-size: 4
      minimum-idle: 0
  flyway:
    enabled: true
    locations: classpath:db/migration
    default-schema: operations
    schemas: operations
    create-schemas: true

server:
  servlet:
    session:
      cookie:
        http-only: true
        same-site: lax
        secure: false

persefonia:
  security:
    admin-access:
      required-oidc-group: admin
      automatic-provisioning-enabled: false
      initial-owner-bootstrap-enabled: true
